###
POST http://localhost:8189/api/v1/student/
Content-Type:application/json

{
"name": "Петров",
 "age": "16"}

####
GET  http://localhost:8189/api/v1/student/
Accept: application/json

####
GET  http://localhost:8189/api/v1/student/10
Accept: application/json

####
DELETE  http://localhost:8189/api/v1/student/1
Accept: application/json

####
PUT  http://localhost:8189/api/v1/student/
Content-Type:application/json

{
"id": "1",
"name": "Алиев",
 "age": "60"}